---
# tasks file for beastlex.vsftpd
#
- name: Install vsftpd package
  package:
    name: vsftpd
    state: latest

- name: Configure vsftpd
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
    owner: root
    group: root
    mode: 0644

- name: Create root dir for anonymous
  file:
    path: "{{ dir_for_anonymous }}"
    state: directory
    owner: root
    group: root
    mode: 0744

- name: Create subdirs for upload
  file:
    path: "{{ dir_for_anonymous}}/{{ item }}"
    state: directory
    mode: 0755
  loop: "{{ subdirs_for_upload }}"
  notify: Restart vsftpd service

- name: Open ports for firewall
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    permanent: true
  loop: "{{ ports_for_open }}"

- name: Restart firewall to apply changes
  service:
    name: firewalld
    state: restarted

- name: Set SELinux boolean
  seboolean:
    name: ftpd_anon_write
    state: "{{ ftpd_anon_write }}"
    persistent: yes
